services:
  - type: web
    name: expert-system-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    healthCheckPath: "/health/"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: expert-system-db
          property: connectionString

databases:
  - name: expert-system-db
    databaseName: expert-system
    user: expert-system_user